Forms featue
herokudev/Rails-blog-app pull request #6
Opened 2021-12-15 22:54 UTC by herokudev

- Use preprocessed HTML file with embedded Ruby code.
- Use layouts and templates for shared content.
- Create forms to perform posts and comments.
- Allow Users to add likes to Posts.

2021-12-15 23:25 UTC, DeliceLydia requested changes
## Hi @herokudev, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._



### Cheers and Happy coding!👏👏👏

Feel free to leave a question, or a comment on the PR thread if something is not clear 100%. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-15 23:25 UTC, DeliceLydia commented on app/controllers/posts_controller.rb
> +    @post = @user.posts.create(params.require(:post).permit(:title, :text))
- [ ] Please create private methods you can call it `post_params` and use it anywhere you want to use `title` and `text`
````ruby
def post_params
      params.require(:post).permit(:title, :text)
    end
````

2021-12-15 23:25 UTC, DeliceLydia commented on app/controllers/comments_controller.rb
> +    @comment = @user.comments.new(params.require(:comment).permit(:text))
- [ ] Same here create private method `comments_params` to use it anytime
````ruby
 def comment_params
    params.require(:comment).permit(:text)
  end
````

2021-12-15 23:25 UTC, DeliceLydia commented on app/views/users/show.html.erb
>           <% @posts.each do |post| %>
- [ ] Check in the `user_card_html.erb` file there is a typo error in your picture you typed `'profile-pic.jpg'` instead of `profile-pic.png` that is why I am getting this error
![phn](https://user-images.githubusercontent.com/44745855/146280199-ddeef028-9c21-4e3c-9953-8e238fd405ee.png)

2021-12-16 00:38 UTC, Lameck1 commented on app/views/users/show.html.erb
>           <% @posts.each do |post| %>
Solved ✔️

2021-12-16 00:38 UTC, Lameck1 commented on app/controllers/comments_controller.rb
> +    @comment = @user.comments.new(params.require(:comment).permit(:text))
Almost there

2021-12-16 00:38 UTC, Lameck1 commented on app/controllers/posts_controller.rb
> +    @post = @user.posts.create(params.require(:post).permit(:title, :text))
Almost there

2021-12-16 00:57 UTC, Lameck1 requested changes
Hi, @herokudev, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-16 00:57 UTC, Lameck1 commented on app/controllers/comments_controller.rb
> +  end
- [ ] You've done well making this change. However, this should be a `private` method just as the previous reviewer mentioned. Why should these methods be private? It is because this method should not be called from any external object but the Controller Class. It also adds security to the App.

## How to handle this:

```ruby
class CommentsController < ApplicationController
  def new
    # new action logic here
  end

  def create
    # create action logic here
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end
```

After defining all the controller actions, at the bottom of the class, add the keyword **`private`** and then move the **`comment_params`** private method below the **`private`** keyword.

2021-12-16 00:57 UTC, Lameck1 commented on app/controllers/posts_controller.rb
> +  end
- [ ] Just as discussed above, please do the same to this `post_params` method. Something like:

```ruby
class PostsController < ApplicationController
  def index
    # index action logic here
  end

  def show
    # show action logic here
  end

  def new
    # new action logic here
  end

  def create
    # create action logic here
  end

  private
 
  def post_params
    params.require(:post).permit(:title, :text)
  end  
end
```

2021-12-16 15:04 UTC, Dipeshtwis approved these changes
# Status: Approved ✔️

## Hi @herokudev, 

Good job on implementing the suggested changes. Well Done.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-16 15:59 UTC, merged