Validations and test
herokudev/Rails-blog-app pull request #7
Opened 2021-12-16 23:45 UTC by herokudev

- Use validations for models.
- Write unit tests for models.
- Secure app from n+1 problems.
- Add flash messages.

2021-12-17 00:13 UTC, mke2111 requested changes
### Hey @herokudev, 

**This is a great project you have going on, well-done lad**. 

   
**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

## Required Changes ♻️
_Check the inline comments under the review for sections to improve._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-17 00:16 UTC, mke2111 commented on app/controllers/posts_controller.rb
>    end
- [ ] In line 4, within the post#index action, you should solve the N+1 problem when fetching all the posts and their comments and likes for a user. Read about the `includes` method in ruby when solving the N+1 problem.

2021-12-17 00:18 UTC, mke2111 commented on spec/models/comment_spec.rb
> +  end
- [ ] This test case is failing. See the screengrab below and give this method a quick fix.
![Screenshot from 2021-12-17 03-10-10](https://user-images.githubusercontent.com/65501535/146467827-60f31398-8289-432d-b9f9-598232f7401d.png)

2021-12-17 23:11 UTC, rloterh requested changes
Hi Herbert, 

You did great on this project, and for making the changes requested in the previous review(s)! 👏👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦  🚦  

## Good Points 👍  
- No linter errors

## Required Changes ♻️
_Kindly check the comments below. Please take your time to carefully improve aspects outlined in the previous code review(s), and please check to see that the changes implemented are working as intended._


<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 1 more limited review per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-17 23:11 UTC, rloterh commented on spec/models/comment_spec.rb
> +  it 'should be equal to zero if there are no recent posts' do
This section requires further improvement:
- [ ] A test case is failing here. Kindly ensure to improve upon this aspect.

**Failing test case:**
![image](https://user-images.githubusercontent.com/12745474/146617567-ce65b2aa-7259-4141-b1d5-88cdb9b8220c.png)

2021-12-17 23:11 UTC, rloterh commented on spec/models/comment_spec.rb
> +  it 'should be equal to zero if there are no recent posts' do
- [ ] The issue regarding post controller is not properly resolved, on line 4 of your `posts_controller.rb`. You can improve this aspect by doing similar:
```
 @posts = @user.posts.includes(:comments) 
```

2021-12-18 00:17 UTC, Dipeshtwis approved these changes
# Status: Approved ✔️

## Hi @herokudev,

Good job on implementing the suggested changes. Well Done.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-18 14:45 UTC, merged